"""empty message

Revision ID: 972f497bf6a2
Revises: 
Create Date: 2024-08-21 19:14:03.088703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972f497bf6a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month',
    sa.Column('month', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('adImpressions', sa.Integer(), nullable=True),
    sa.Column('annotationClickableImpressions', sa.Integer(), nullable=True),
    sa.Column('annotationClicks', sa.Integer(), nullable=True),
    sa.Column('annotationClickThroughRate', sa.Float(), nullable=True),
    sa.Column('annotationClosableImpressions', sa.Integer(), nullable=True),
    sa.Column('annotationCloses', sa.Integer(), nullable=True),
    sa.Column('annotationCloseRate', sa.Float(), nullable=True),
    sa.Column('annotationImpressions', sa.Integer(), nullable=True),
    sa.Column('audienceWatchRatio', sa.Float(), nullable=True),
    sa.Column('averageViewDuration', sa.Float(), nullable=True),
    sa.Column('averageViewPercentage', sa.Float(), nullable=True),
    sa.Column('cardClickRate', sa.Float(), nullable=True),
    sa.Column('cardClicks', sa.Integer(), nullable=True),
    sa.Column('cardImpressions', sa.Integer(), nullable=True),
    sa.Column('cardTeaserClickRate', sa.Float(), nullable=True),
    sa.Column('cardTeaserClicks', sa.Integer(), nullable=True),
    sa.Column('cardTeaserImpressions', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('estimatedMinutesWatched', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('playbackBasedCpm', sa.Float(), nullable=True),
    sa.Column('playlistStarts', sa.Integer(), nullable=True),
    sa.Column('savesAdded', sa.Integer(), nullable=True),
    sa.Column('savesRemoved', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('subscribersGained', sa.Integer(), nullable=True),
    sa.Column('subscribersLost', sa.Integer(), nullable=True),
    sa.Column('videosAddedToPlaylists', sa.Integer(), nullable=True),
    sa.Column('videosRemovedFromPlaylists', sa.Integer(), nullable=True),
    sa.Column('viewerPercentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('month')
    # ### end Alembic commands ###
